0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,28 @@
 #!/usr/bin/env bash
-#transfers file to server's home directory
-if [[ $# -ne 4 ]]
+# checking for command line arguments
+
+if [ $# -lt 4 ]
 then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
-scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+
+# assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabling strict host key checking
+
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+	echo "FILE TRANSFER FAILED"
+fi
